title Starting Script
pause
start
title Launched Script!
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
echo hellooooooooo
pause
